#!/bin/sh

set -e

case "$1" in
    configure)
        # create a achelous group and user
        if ! getent passwd achelous >/dev/null 2>&1; then
            addgroup --system --gid 899 achelous
            adduser --system --uid 899 --gid 899 --home /var/spool/achelous achelous
        fi

        # create spool dir
        if [ ! -d /var/spool/achelous ]; then
            mkdir -p /var/spool/achelous
            chown achelous:achelous /var/spool/achelous
            chmod 750 /var/spool/achelous
        fi

        # enable systemd service
        deb-systemd-helper enable achelous-upstream.service >/dev/null || true
        deb-systemd-invoke restart achelous-upstream.service >/dev/null || true

        # enable rc.d service
        update-rc.d achelous-upstream defaults || true
        invoke-rc.d achelous-upstream restart || true
    ;;
esac
