# -*- mode: ruby -*-
# vi: set ft=ruby :

# Note: Detect used sendmail params with the help of strace, e.g.
# strace -f -e trace=process mail ...

Vagrant.configure("2") do |config|

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.define "achelous" do |achelous|
    achelous.vm.box = "ubuntu/xenial64"
    achelous.vm.hostname = 'achelous'
    achelous.vm.network :private_network, ip: "192.168.56.101"
    achelous.vm.provision "file", source: "../.build/dist/achelous_1.0-1_amd64.deb", destination: "achelous_1.0-1_amd64.deb"
    achelous.vm.provision "file", source: "./upstream.json", destination: "upstream.json"
    achelous.vm.provision "shell", inline: <<-SHELL
      mkdir /etc/achelous
      mv upstream.json /etc/achelous/
      apt-get -qq update
      apt-get -qq dist-upgrade
      apt-get -y -qq install mc jq
      dpkg -i achelous_1.0-1_amd64.deb
      apt-get -y -qq install mailutils
    SHELL
  end

  config.vm.define "testservice" do |testservice|
    testservice.vm.box = "ubuntu/xenial64"
    testservice.vm.hostname = 'testservice'
    testservice.vm.network :private_network, ip: "192.168.56.102"
    testservice.vm.provision "file", source: "./testservice/main.js", destination: "main.js"
    testservice.vm.provision "file", source: "./testservice/package.json", destination: "package.json"
    testservice.vm.provision "file", source: "./testservice/achelous-testservice.service", destination: "achelous-testservice.service"
    testservice.vm.provision "shell", inline: <<-SHELL
      apt-get -qq update
      apt-get -qq dist-upgrade
      apt-get -y -qq install mc jq
      curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      sudo apt-get -y -qq install nodejs
      adduser --disabled-password --gecos "" testservice
      mv main.js package.json /home/testservice/
      su -l -c 'npm install' testservice
      mv achelous-testservice.service /lib/systemd/system/
      systemctl enable achelous-testservice.service
      systemctl start achelous-testservice.service
    SHELL
  end

end
